- name: "Maxi-Cosi FamilyFix 360"
  originalPrice: "169.00"
  urls:
    - "https://www.bol.com/nl/nl/p/maxi-cosi-familyfix-360-i-size-isofix-autostoel-base-essential-grey/9300000074243531/?bltgh=oFC61UoF9XGrD3D6jvlDPw.4_8.9.ProductTitle"
    - "https://www.babypark.nl/maxi-cosi-familyfix-360.html"
    - "https://www.vanastenbabysuperstore.nl/isofixbase-maxi-cosi-familyfix-360"